### ISSUE TITLE
Crate is not published

### ISSUE THREAD

**Issue by rosshadden** [darfink/jsrt-rs#1]
It doesn't seem that `chakracore` is published, though `chakracore-sys` is.

Btw thanks for this project, I'm hoping to use it in a thing.  It's not immediately clear what works or what doesn't, but if I run into something I know I can just use `chakracore-sys` like you mentioned.

**Comment by rawsp33d** [comment]
Also it seems that `libbindgen` was ["yanked"](https://crates.io/crates/libbindgen) from cargo.  TIL that was a thing.

**Comment by rawsp33d** [comment]
Looks like they renamed it to just [bindgen](https://github.com/servo/rust-bindgen), though the versions don't match up, so maybe not.

**Comment by rawsp33d** [comment]
Fixed the `libbindgen` thing in #2.  The main issue subject still applies :).

**Comment by darfink** [comment]
The reason I have not yet published `chakracore` is because I have not implemented support for values on the heap (i.e they may be dropped prematurely).

Chakracore analyses the stack to determine whether the values should be kept alive or not.
I may however decide to publish it anyway with a disclaimer until this has been implemented.

**Comment by darfink** [comment]
I've decided to publish the crate in its current condition: https://crates.io/crates/chakracore
