### ISSUE TITLE
Can't build to target musl on Ubuntu

### ISSUE THREAD

**Issue by corbinu** [darfink/jsrt-rs#16]
Sorry I feel like I am going to be that annoying guy who doesn't ever know whats going on but I was trying to build on Ubuntu now and the normal target works. 

However I wanted to build targeting musl so libc is build into the binary (lets it run on any linux system and a FROM scratch docker container)

I then get this 
```
cargo run --target=x86_64-unknown-linux-musl
   Compiling rocket_contrib v0.2.8
   Compiling chakracore-sys v0.2.2
error: failed to run custom build command for `chakracore-sys v0.2.2`
process didn't exit successfully: `/home/corbinu/Developer/corbinu/rocket-challenge/target/debug/build/chakracore-sys-795c32afd2d7755e/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=CHAKRA_SOURCE
cargo:rerun-if-env-changed=CHAKRA_BUILD
/usr/bin/pkg-config
chakracore-sys/build.rs:51: Using default ChakraCore build (version: 1.5.1)
chakracore-sys/build.rs:103: Binaries already built, using existing...
cargo:rustc-link-search=native=/home/corbinu/Developer/corbinu/rocket-challenge/target/x86_64-unknown-linux-musl/debug/build/chakracore-sys-201a0b8ad8cf6a2f/out/lib-1.5.1
cargo:rustc-link-lib=static=ChakraCoreStatic

--- stderr
thread 'main' panicked at 'No package configuration for 'libunwind-ptrace' found', /checkout/src/libcore/option.rs:823
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I tried installing `libunwind-dev` and that din't help any thoughts?

**Comment by darfink** [comment]
It seems pkg-config cannot find `libunwind-ptrace`.
You would need to build it and link against [musl](http://wiki.musl-libc.org/wiki/BuildingLLVM#Build_libunwind), to have a standalone executable.

But besides this I do not believe you can achieve what you desire.
Since this library uses [Microsoft/ChakraCore](https://github.com/Microsoft/ChakraCore), it has the same dependencies.

ChakraCore is developed in C++, and therefore it dynamically links against `stdc++`, so regardless of whether you link against musl or not, the application would still not be a standalone executable (musl is only a replacement for the C library).

Although it may be possible if you build `stdc++` and link it against musl, but this is not possible/supported from what I can tell.

**Comment by corbinu** [comment]
Ahh to bad well that's ok no worries.
